### ISSUE TITLE
Support posting multiple service metrics at once

### ISSUE THREAD

**Issue by stefafafan** [stefafafan/post-mackerel-metrics#19]
API supports an array to POST multiple metrics at once: https://mackerel.io/api-docs/entry/service-metrics#post .

Maybe we should add something like this? 🤔  Hmm...

```yaml
uses: stefafafan/post-mackerel-metrics@v1
with:
  api-key: ${{ secrets.MACKEREL_APIKEY }}
  service-name: ${{ secrets.MACKEREL_SERVICENAME }}
  metrics: |
    [
      {
        "name": "my-favorite-metric.count",
        "value": 123
      },
      {
        "name": "my-favorite-metric2.count",
        "value": 111
      },
      {
        "name": "my-favorite-metric3.count",
        "value": 222
      }
    ]
```

**Comment by stefafafan** [comment]
Related: https://github.com/community/community/discussions/11692

**Comment by stefafafan** [comment]
`name,value` space separated?
```yaml
uses: stefafafan/post-mackerel-metrics@v1
with:
  api-key: ${{ secrets.MACKEREL_APIKEY }}
  service-name: ${{ secrets.MACKEREL_SERVICENAME }}
  metrics: "my-favorite-metric.count,123 my-favorite-metric2.count,111 my-favorite-metric3.count,222"
```

`name:value` comma separated?
```yaml
uses: stefafafan/post-mackerel-metrics@v1
with:
  api-key: ${{ secrets.MACKEREL_APIKEY }}
  service-name: ${{ secrets.MACKEREL_SERVICENAME }}
  metrics: "my-favorite-metric.count:123,my-favorite-metric2.count:111,my-favorite-metric3.count:222"
```

`name value` newline separated?
```yaml
uses: stefafafan/post-mackerel-metrics@v1
with:
  api-key: ${{ secrets.MACKEREL_APIKEY }}
  service-name: ${{ secrets.MACKEREL_SERVICENAME }}
  metrics: |
    my-favorite-metric.count 123
    my-favorite-metric2.count 111
    my-favorite-metric3.count 222
```
